main/blueprints/auth.py
from flask import Blueprint, redirect, url_for, request, flash, render_template, session
from flask_login import current_user, login_user, login_required, logout_user
from main.models import User
from main.extensions import db
from main.forms import RegisterForm, LoginForm
from main.utilities import redirect_back

auth_bp = Blueprint('auth',__name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('You already log in.')
        return redirect(url_for('index.index'))
    print("check login")
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None:
            password = form.password.data
            if user.verify_password(password):
                print("login in success")
                remember = form.remember.data
                login_user(user,remember)
                return redirect(url_for('chat.platform'))
            else:
                flash('You email or password is wrong, please try again')
        else:
            flash('Sorry, the account doesn`t exist.')
    return render_template("auth/login.html", form = form)
    
    

@auth_bp.route('/logout')
@login_required
def logout():
    # session['id'] = current_user.id
    logout_user()
    # return redirect(url_for('chat.leave_room'))
    return redirect_back()


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        email = request.form['email'].lower()
        user = User.query.filter_by(email=email).first()
        print(user)
        if user is not None:
            flash('The email is already registered, please log in.')
            return redirect(url_for('auth.login'))
        nickname = request.form['nickname']
        password = request.form['password1']
        user = User(email=email, nickname=nickname)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        flash('Registered successful, please log in.')
        return redirect(url_for('auth.login'))

    return render_template('auth/register.html', form=form)

main/blueprints/chat.py
import random
from flask import Blueprint, render_template, redirect, url_for, flash, request, session, current_app ,jsonify
from flask_login import current_user
from main.extensions import db, redis
from main.models import User, Message, Room, Word

chat_bp = Blueprint('chat',__name__)


# redis describtion
# There are serveral type use in redis
# Set type: the key is "room", value is stored each of room name;
# Zset type: the key is "room name" + "_score", which store the players in the room and their scores.
# Hash type: 3.1 the key is "roomstatus", the field is each of room name, the value is the room status, if 1 that
#    means it's on the game, else means off the game.
#    3.2 the key is each of room name, and the field is each of room member, the value is user's status, if 1 that
#    means he is ready, else means not. Default is 0.
#    3.3 the key is "topic", and the field is  each of room name. the value is the answer of the room.


@chat_bp.before_request
def before_request():
    if not current_user.is_authenticated:
        return current_app.login_manager.unauthorized()
    pass

@chat_bp.route('/platform')
def platform():
    rooms = Room.query.all()
    leaders = { room.leader for room in rooms}
    leader_dict = { name:User.query.filter_by(nickname=name).first().gravatar for name in leaders}
    return render_template('platform.html', rooms=rooms, leaders=leader_dict)


@chat_bp.route('/room/<string:rn>')
def room(rn):
    room = Room.query.filter_by(name=rn).first()
    if current_user not in room.users:
        flash('Sorry, you are not in the room')
        return redirect(url_for('chat.platform'))
    # print(room.name)
    messages = Message.query.filter_by(room=room).order_by(Message.timestamp.asc())[-30:]
    rank = redis.zrevrange(room.name + "_score",0,-1,withscores=True,score_cast_func=int)
    # print(rank)
    rank = dict(rank)
    return render_template('chat/home.html', messages=messages, user=current_user.nickname, room_name=room.name,
                           users=room.users,leader=room.leader, rank=rank)

@chat_bp.route('/create',  methods=['GET', 'POST'])
def create_room():
    name = request.form['name']
    password = request.form['pass']
    room = Room.query.filter_by(name=name).first()
    if room is None and not redis.sismember("room",name):
        new_room = Room(name=name, password=password)
        new_room.set_leader(current_user.nickname)
        db.session.add(new_room)
        db.session.commit()
        # add room name to the name of room in redis set
        redis.sadd("room",name)
        room = Room.query.filter_by(name=name).first()
        room.users.append(current_user)
        db.session.commit()
        redis.zadd(name + "_score",{current_user.nickname:0})
        redis.hset(room.name, current_user.nickname, 0)
        return jsonify(result="success", type="create", data={"room":new_room.name, "room_url":url_for('chat.room', rn=room.name)})
        # return redirect(url_for('chat.join_room', rn=new_room.name))
    return jsonify(result="fail", type="create", message='Sorry, the name is alreay existed, please change another.')

@chat_bp.route('/search',  methods=['POST'])
def search_room():
    print("in search_room")
    name = request.form['room']
    room = Room.query.filter_by(name=name).first()
    if room is not None:
        return jsonify(result="success",type="search", data={'room':room.name, 'is_public': True if room.password else False, 'join_url':url_for('chat.join_room', rn=room.name)})
    return jsonify(result="fail",type="search", message='Can\'t find the room.')


@chat_bp.route('/join/<string:rn>', methods=['POST'])
def join_room(rn):
    room = Room.query.filter_by(name=rn).first()
    if room is None:
        return jsonify(result="fail",type="joinRoom", message="The room doesn't exist.")
    if room.password:
        password = request.form.get("password",None)
        if password != room.password:
            return jsonify(result="fail", type="joinRoom", message="Password is incorrect.")
    if redis.hget("roomstatus", room.name) == "1":
        return jsonify(result="fail", type="joinRoom", message="The room is on the game, please join later.")
    elif (current_user not in room.users) and len(room.users) >= 6:
        return jsonify(result="fail", type="joinRoom", message="Sorry, the room is already full.")
    elif current_user in room.users:
        return jsonify(result="success", type="joinRoom", data={"room": room.name,"room_url": url_for('chat.room', rn=room.name)})
    try:
        room.users.append(current_user)
        db.session.commit()
    except:
        return jsonify(result="fail", type="joinRoom", dmessage="Sorry, the room is already full.")
    redis.zadd(room.name + "_score", {current_user.nickname: 0})
    redis.hset(room.name, current_user.nickname, 0)
    return jsonify(result="success", type="joinRoom",
                   data={"room": room.name, "room_url": url_for('chat.room', rn=room.name)})

@chat_bp.route('/leave/<string:rn>')
def leave_room(rn):
    print(current_user.nickname, "run leave room command")
    room = Room.query.filter_by(name=rn).first()
    if room is not None and current_user in room.users:
        redis.zrem(room.name + "_score", current_user.nickname)
        redis.hdel(room.name, current_user.nickname)
        room.users.remove(current_user)
        if len(room.users) == 0 :
            print("clear the room", room.name)
            redis.srem("room",room.name)
            db.session.delete(room)
        db.session.commit()
    return redirect(url_for('chat.platform'))


@chat_bp.route('/room/<rn>/leader', defaults={'user':None})
@chat_bp.route('/room/<rn>/leader/<user>')
def leader_change(rn,user):
    room = Room.query.filter_by(name=rn).first()
    members = [i.nickname for i in room.users]
    print("in leader change function:",members,room.leader)
    if user and user in members:
        candidate = user
        # leader = room.set_leader(user)
    elif len(members) == 1 and members[0] == room.leader:
        return jsonify(result="success", type="changeLeader", data={"room": room.name, "leader": room.leader})
    else:
        candidate = random.choice([i for i in members if i !=room.leader])
    leader = room.set_leader(candidate)
    db.session.commit()
    print("new leader is ", leader)
    return jsonify(result="success", type="changeLeader", data={"room": room.name, "leader":leader})


@chat_bp.route('/messages/<string:rn>')
def get_messages(rn):
    page = request.args.get('page', 1, type=int)
    room = Room.query.filter_by(name=rn).first()
    pagination = Message.query.filter_by(room=room).order_by(Message.timestamp.desc()).paginate(
        page, per_page=30 ,error_out=False)
    messages = pagination.items
    return render_template('chat/_messages.html', messages=messages[::-1])


@chat_bp.route('/checkanswer/<string:rn>')
def check_answer(rn):
    answer = request.args.get('answer')
    print("check answer:",answer)
    room = Room.query.filter_by(name=rn).first()
    if redis.hget("roomstatus", room.name) == "1":
        correct_answer = redis.hget("topic", room.name)
        if answer.lower() == correct_answer.lower():
            redis.zincrby(room.name + "_score", 10, current_user.nickname)
            score = redis.zscore(room.name + "_score", current_user.nickname)
            return jsonify(result="correct", score=score, room=room.name, user=current_user.nickname)
    return jsonify(result="wrong", room=room.name)


@chat_bp.route('/gettopic/<string:rn>')
def get_topic(rn):
    room = Room.query.filter_by(name=rn).first()
    if current_user.nickname == room.leader:
        word = Word.query.get(random.randint(1, Word.query.count()))
        print(word)
        redis.hset("roomstatus", room.name, 1)
        redis.hset("topic", room.name, word.name)
        print("get topic:",word.name)
        return jsonify(result="success", topic=word.name, room=room.name)
    return jsonify(result="fail", topic=None, room=room.name)


@chat_bp.route('/room/<string:rn>/refreshscores')
def roomscore(rn):
    room = Room.query.filter_by(name=rn).first()
    rank = redis.zrevrange(room.name + "_score", 0, -1, withscores=True, score_cast_func=int)
    rank = dict(rank)
    return jsonify(rank=rank, rank_html=render_template('chat/_ranks.html', users=room.users, rank=rank),
                   room=room.name)


@chat_bp.route('/room/<string:rn>/refreshleader')
def refreshleader(rn):
    room = Room.query.filter_by(name=rn).first()
    return jsonify(leader_html=render_template('chat/_top_bar_status_users.html', users=room.users, leader=room.leader),
                   room=room.name,
                   leader=room.leader)


@chat_bp.route('/room/<string:rn>/ready')
def refreshreadystatus(rn):
    room = Room.query.filter_by(name=rn).first()
    users_status = redis.hgetall(room.name)
    all_ready = True
    for user,status in users_status.items():
        if user != room.leader and status == "0":
            all_ready = False
            break
    print(users_status)
    return jsonify(
        status_html=render_template('chat/_top_bar_status_users.html', users=room.users, leader=room.leader,
                                               status=users_status),
        userStatus=users_status,
        allReady = all_ready,
        room=room.name)

main/templates/chat/_beginOrReady.html
{% if leader == user %}
<div id="leaderprepare" class="ui buttons large">
    <button id="begin" class="ui button orange disabled inputarea-button">Begin</button>
</div>
{% else %}
<div id="guestprepare" class="ui buttons large">
    <button id="ready" class="ui toggle button inputarea-button">Ready</button>
</div>
{% endif %}

main/templates/chat/_canvas.html
{% if leader == user %}
<div id="canvas-tool">
    <div class="ui toggle icon button canvastool-pencil active" id="canvastool-pencil">
        <i class="pencil alternate icon"></i>
        <div class="pencil-menu invisible">
            <div class="range-wrap">
                <input type="range" id="pencil-range" class="slider" min="1" max="30" value="5">
            </div>
            <div id="color-group">
                <ul>
                    <li id="white" class="color-item" style="background-color: white;"></li>
                    <li id="black" class="color-item active" style="background-color: black;"></li>
                    <li id="red" class="color-item" style="background-color: #FF3333;"></li>
                    <li id="blue" class="color-item" style="background-color: #0066FF;"></li>
                    <li id="yellow" class="color-item" style="background-color: #FFFF33;"></li>
                    <li id="green" class="color-item" style="background-color: #33CC66;"></li>
                    <li id="gray" class="color-item" style="background-color: gray;"></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="ui toggle icon button canvastool-eraser" id="canvastool-eraser">
        <i class="eraser icon"></i>
        <div class="eraser-menu invisible">
            <div class="range-wrap">
                <input type="range" id="eraser-range" class="slider" min="1" max="60" value="30">
            </div>
        </div>
    </div>
</div>
<div id="question" class="ui card">
    <div class="content">
        <div class="header">Topic</div>
        <div class="description"></div>
    </div>
</div>
<div id="reSetCanvas" class="ui icon button canvastool-trash">
    <i class="trash alternate icon"></i>
</div>
{% else %}
<div class="ui icon button toggle canvastool-answer active">
    <i class="keyboard icon"></i>
</div>
<div id="answer" class="ui card">
    <div class="content">
        <div class="header">Answer:</div>
        <div class="description"><i id="checkanswer" class="icon"></i></div>

    </div>
</div>
{% endif %}

main/templates/chat/_join_leave_message.html
<div class="msg-box">
    <div class="msg">
        <small class="message-body">{{ user }} {{ message }}</small>
    </div>
</div>

main/templates/chat/_message.html
<div class="msg-box">
    <div class="msg-picture">
        <img class="pop-card" data-position="right center" data-offset="-40" src="{{ message.user.gravatar }}">
    </div>
    <div class="msg">
        <span class="msg-nickname">{{ message.user.nickname }}</span>
        <small class="msg-timestamp">{{ moment(message.timestamp).format('lll') }}</small>
        <span class="msg-body">{{ message.body|safe }}</span>
    </div>
</div>

main/templates/chat/_messages.html
{% for message in messages %}
    {% include "chat/_message.html" %}
{% endfor %}

main/templates/chat/_new_message.html
<div class="msg-box">
    <div class="msg-picture">
        <img class="pop-card" data-position="right center" data-offset="-40" src="{{ message.user.gravatar }}">
    </div>
    <div class="msg">
        <span class="msg-nickname">{{ message.user.nickname }}</span>
        <small class="msg-timestamp">{{ moment(message.timestamp).format('lll') }}</small>
        <span class="msg-body">{{ message.body|safe }}</span>
    </div>
</div>

main/templates/chat/_rank.html
<div class="item rank-item">
    <img class="ui avatar image hide-on-mobile" src="{{ user.gravatar }}">
    <div class="content">
        <div class="header">{{ user.nickname }}</div>
        <div class="point">{{ rank[user.nickname] }}</div>
    </div>
</div>

main/templates/chat/_ranks.html
{% for user in users %}
    {% include "chat/_rank.html" %}
{% endfor %}

main/templates/chat/_room.html
{#
<div class="item">
    <div class="right floated content">
        <button class="ui button" data-url="{{ url_for('chat.join_room', rn=room.name) }}"
                data-public="{% if room.password %}false{% else %}true{% endif %}"
                data-room="{{ room.name }}">
            {% if room.password %}
                <i class="lock icon"></i>
            {% endif %}
            Join
        </button>
    </div>
<!--    <img class="ui avatar image" src="{{ leaders[room.leader] }}">-->
<!--    <div class="content">-->
<!--        <h5 class="header">-->
<!--            {{ room.leader }}</h5>-->
<!--        <div class="description">Room: {{ room.name }}</div>-->
<!--    </div>-->
    <h3 class="ui grey header">
        <img class="ui avatar image" src="{{ leaders[room.leader] }}">
          <div class="content">
            {{ room.leader }}
            <div class="sub header">Room: {{ room.name }}</div>
          </div>
    </h3>
</div>
#}



<div class="item">
    <div class="ui small image">
      <img src="{{ leaders[room.leader] }}">
    </div>
    <div class="middle aligned content">
      <div class="header">
        {{ room.leader }}
      </div>
      <div class="description">
        Room: {{ room.name }}
      </div>
      <div class="extra">
                <button class="ui button" data-url="{{ url_for('chat.join_room', rn=room.name) }}"
                data-public="{% if room.password %}false{% else %}true{% endif %}"
                data-room="{{ room.name }}">
            {% if room.password %}
                <i class="lock icon"></i>
            {% endif %}
            Join
        </button>
      </div>
    </div>
  </div>

main/templates/chat/_top_bar_status_users.html
{% for user in users %}
    <div class="ui image label user-on-mobile">
        {{ user.nickname }}
        {% if leader == user.nickname %}
            {% if status and status[user.nickname] == "1" %}
                <i class="user icon check circle green"></i>
            {% else %}
                <i class="user icon"></i>
            {% endif %}
        {% else %}
            {% if status and status[user.nickname] == "1" %}
                <i class="icon check circle green"></i>
            {% else %}
                <i class="icon"></i>
            {% endif %}
        {% endif %}
    </div>
{% endfor %}

main/templates/chat/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ room_name }} - Guess What I Draw</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
<!--    <link rel="icon" href="{{ url_for('static', filename='images/logo.png') }}">-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/room.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/countdown.css') }}">
    <!--    <link rel="stylesheet" href="{{ url_for('static', filename='css/test.css') }}">-->
</head>
<body>


<div class="pusher">
    <div id="container" class="ui grid">
        <!--navigation area-->
        <div class="row navigation">
            <div class="column">
                <div class="ui top fixed borderless menu navigation-bar">
                    <div class="ui large buttons">
                        <button class="ui button teal quit change-on-mobile" id="leave-button"
                                data-url="{{ url_for('chat.leave_room', rn=room_name ) }}">QUIT
                        </button>
                    </div>
                    <div class="item change-on-mobile">
                        <div class="ui label black basic change-on-mobile" id="user-online">
                            {% include 'chat/_top_bar_status_users.html' %}
                        </div>
                    </div>
                    <div class="right menu hide-on-mobile">
                        <div class="item">
                            <button class="ui button orange basic" data-room="{{ room_name }}" id="room_id">Room: {{
                                                                                                            room_name }}
                            </button>
                        </div>
                        <a class="item" id="toggle-sidebar">
                            <i class="sidebar icon"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <!--drawing area-->
        <div id="canvas" class="row">
            <div class="column">
                <div class="canvas-container">
                    <div id="refreshcanvas">
                        {% include 'chat/_canvas.html' %}
                    </div>
                    <div class="ui icon button toggle canvastool-rank active">
                        <i class="trophy icon"></i>
                    </div>
                    <div id="rank" class="ui list flex-on-mobile">
                        {% include "chat/_ranks.html" %}
                    </div>
                    <canvas id="myCanvas" class="quiz"></canvas>
                    <div id="countdown"></div>
                    <div id="snackbar">Someone answer is correct</div>
                </div>
            </div>
        </div>

        <!--all messages area-->
        <div id="message-area" class="row" data-url="{{ url_for('chat.get_messages', rn=room_name) }}">
            <div class="column">
                {% block messages %}{% endblock %}
                <div class="messages">
                    <div class="ui text loader">Loading messages...</div>
                    {% include 'chat/_messages.html' %}
                </div>
            </div>
        </div>

        <!--reply message area-->
        <div id="message-input-area" class="row">
            {% block inputarea %}{% endblock %}
            {% if current_user.is_authenticated %}
            <div class="twelve wide column">
                <div class="input-area">
                    <img class="pop-card input-avatar" data-position="bottom left" src="{{ current_user.gravatar }}">
                    <textarea rows="2" id="message-textarea"
                              placeholder="Write your message here... Enter to send"></textarea>
                </div>
            </div>
            <div class="four wide column" id="beginOrReady-button">
                {% include "chat/_beginOrReady.html" %}
            </div>
            {% else %}
            <div class="ui floating message">Please <a href="{{ url_for('auth.login') }}">Sign in</a> or
                <a href="{{ url_for('auth.register') }}">Sign up</a> to send message.
            </div>
            {% endif %}
        </div>
    </div>
</div>


<!-- Sidebar Menu -->
<!--<div class="ui labeled icon right vertical inverted menu sidebar">-->
<!--    <a class="item" href="{{ url_for('auth.logout') }}">-->
<!--        <i class="power off icon"></i>Sign out-->
<!--    </a>-->
<!--</div>-->
<div class="ui vertical right inverted sidebar menu">
    {% if current_user.is_authenticated %}
    <a class="active item">
        <div id="sidebar-leave-button">
            Back to platform
        </div>
    </a>
    <a href="{{ url_for('auth.logout') }}" class="item">Log out</a>
    {% else %}
    <a href="{{ url_for('auth.login') }}" class="item">Log in</a>
    <a href="{{ url_for('auth.register') }}" class="item">Sign up</a>
    {% endif %}
</div>

<!-- Countdown Modal -->
<div class="ui basic modal transition hidden">
    <div class="content">
        <div class="center">
            <div class="countdown">
                <div class="countdown__colored-blocks">
                    <div class="countdown__colored-blocks-rotater">
                        <div class="countdown__colored-block"></div>

                    </div>
                    <div class="countdown__colored-blocks-inner"></div>
                    <div class="countdown__text">Ready</div>
                </div>
                <div class="countdown__inner">
                    <svg class="countdown__numbers" viewBox="0 0 100 100">
                        <path class="countdown__numbers-path"
                              d="M-10,20 60,20 40,50 a18,15 0 1,1 -12,19
               Q25,44 34.4,27.4
               l7,-7 a16,16 0 0,1 22.6,22.6 l-30,30 l35,0 L69,73
               a20,10 0 0,1 20,10 a17,17 0 0,1 -34,0 L55,83
               l0,-61 L40,28" />
                    </svg>
                </div>
            </div>
        </div>
    </div>
</div>



{% block script %}
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.js"
        integrity="sha512-aMGMvNYu8Ue4G+fHa359jcPb1u+ytAF+P2SCb+PxrjCdO3n3ZTxJ30zuH39rimUggmTwmh2u7wvQsDTHESnmfQ=="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
<script src="{{ url_for('static', filename='js/canvas.js') }}"></script>
<script src="{{ url_for('static', filename='js/additional_socket.js') }}"></script>
<script src="{{ url_for('static', filename='js/drawing_script.js') }}"></script>
{{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";
    var refresh_score_url = "{{  url_for('chat.roomscore', rn=room_name) }}";
    var refresh_leader_url = "{{  url_for('chat.refreshleader', rn=room_name) }}";
    var refresh_ready_url = "{{  url_for('chat.refreshreadystatus', rn=room_name) }}";
    var change_leader_url = "{{  url_for('chat.leader_change', rn=room_name) }}";
    var current_user_name = "{{ current_user.nickname|default(0) }}";
    var check_answer_url = "{{ url_for('chat.check_answer', rn=room_name) }}";
    var get_topic = "{{ url_for('chat.get_topic', rn=room_name) }}";

    $(document).ready(function () {
    });
    var drawer = {
      value: "{{ leader|safe }}",
      get getVar() {
        return this.value;
      },
      set saveVar(value) {
        this.value = value;
        Initcanvas();
      }
    }


</script>
{% endblock %}
</body>
</html>

main/templates/chat/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}
{% block nav %}{% endblock %}

{% block content %}
    <div class="ui middle aligned center aligned grid">
        <div class="column">
            <div class="ui attached message">
                <div class="header ui image ">
                    <img src="{{ url_for('static', filename='logo.png') }}" class="image">
                    <div class="content">Tell us about you!</div>
                </div>
            </div>
            <form class="profile ui form attached left aligned fluid segment" method="post"
                  action="{{ url_for('chat.profile') }}">
                <div class="field eight wide">
                    <label>Nickname</label>
                    <input name="nickname" placeholder="Nickname" type="text" value="{{ current_user.nickname }}">
                </div>
                <div class="field">
                    <label>GitHub</label>
                    <input name="github" placeholder="https://github.com/greyli" type="text"
                           value="{{ current_user.github or '' }}">
                </div>
                <div class="field">
                    <label>Website</label>
                    <input name="website" placeholder="http://greyli.com" type="text"
                           value="{{ current_user.website or '' }}">
                </div>
                <div class="field">
                    <label>Bio</label>
                    <input name="bio" placeholder="I'm a ..." type="text" value="{{ current_user.bio or '' }}">
                </div>
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <div class="fields two">
                    <div class="ui orange submit fluid button">Start Chat</div>
                </div>
            </form>
            {% for error_message in get_flashed_messages() %}
                <div class="ui message floating warning closeable">
                    <i class="close icon"></i>
                    <div>{{ error_message }}</div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}