main/blueprints/auth.py
from flask import Blueprint, redirect, url_for, request, flash, render_template, session
from flask_login import current_user, login_user, login_required, logout_user
from main.models import User
from main.extensions import db
from main.forms import RegisterForm, LoginForm
from main.utilities import redirect_back

auth_bp = Blueprint('auth',__name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('You already log in.')
        return redirect(url_for('index.index'))
    print("check login")
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None:
            password = form.password.data
            if user.verify_password(password):
                print("login in success")
                remember = form.remember.data
                login_user(user,remember)
                return redirect(url_for('chat.platform'))
            else:
                flash('You email or password is wrong, please try again')
        else:
            flash('Sorry, the account doesn`t exist.')
    return render_template("auth/login.html", form = form)
    
    

@auth_bp.route('/logout')
@login_required
def logout():
    # session['id'] = current_user.id
    logout_user()
    # return redirect(url_for('chat.leave_room'))
    return redirect_back()


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        email = request.form['email'].lower()
        user = User.query.filter_by(email=email).first()
        print(user)
        if user is not None:
            flash('The email is already registered, please log in.')
            return redirect(url_for('auth.login'))
        nickname = request.form['nickname']
        password = request.form['password1']
        user = User(email=email, nickname=nickname)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        flash('Registered successful, please log in.')
        return redirect(url_for('auth.login'))

    return render_template('auth/register.html', form=form)

main/blueprints/chat.py
import random
from flask import Blueprint, render_template, redirect, url_for, flash, request, session, current_app ,jsonify
from flask_login import current_user
from main.extensions import db, redis
from main.models import User, Message, Room, Word

chat_bp = Blueprint('chat',__name__)


# redis describtion
# There are serveral type use in redis
# Set type: the key is "room", value is stored each of room name;
# Zset type: the key is "room name" + "_score", which store the players in the room and their scores.
# Hash type: 3.1 the key is "roomstatus", the field is each of room name, the value is the room status, if 1 that
#    means it's on the game, else means off the game.
#    3.2 the key is each of room name, and the field is each of room member, the value is user's status, if 1 that
#    means he is ready, else means not. Default is 0.
#    3.3 the key is "topic", and the field is  each of room name. the value is the answer of the room.


@chat_bp.before_request
def before_request():
    if not current_user.is_authenticated:
        return current_app.login_manager.unauthorized()
    pass

@chat_bp.route('/platform')
def platform():
    rooms = Room.query.all()
    leaders = { room.leader for room in rooms}
    leader_dict = { name:User.query.filter_by(nickname=name).first().gravatar for name in leaders}
    return render_template('platform.html', rooms=rooms, leaders=leader_dict)


@chat_bp.route('/room/<string:rn>')
def room(rn):
    room = Room.query.filter_by(name=rn).first()
    if current_user not in room.users:
        flash('Sorry, you are not in the room')
        return redirect(url_for('chat.platform'))
    # print(room.name)
    messages = Message.query.filter_by(room=room).order_by(Message.timestamp.asc())[-30:]
    rank = redis.zrevrange(room.name + "_score",0,-1,withscores=True,score_cast_func=int)
    # print(rank)
    rank = dict(rank)
    return render_template('chat/home.html', messages=messages, user=current_user.nickname, room_name=room.name,
                           users=room.users,leader=room.leader, rank=rank)

@chat_bp.route('/create',  methods=['GET', 'POST'])
def create_room():
    name = request.form['name']
    password = request.form['pass']
    room = Room.query.filter_by(name=name).first()
    if room is None and not redis.sismember("room",name):
        new_room = Room(name=name, password=password)
        new_room.set_leader(current_user.nickname)
        db.session.add(new_room)
        db.session.commit()
        # add room name to the name of room in redis set
        redis.sadd("room",name)
        room = Room.query.filter_by(name=name).first()
        room.users.append(current_user)
        db.session.commit()
        redis.zadd(name + "_score",{current_user.nickname:0})
        redis.hset(room.name, current_user.nickname, 0)
        return jsonify(result="success", type="create", data={"room":new_room.name, "room_url":url_for('chat.room', rn=room.name)})
        # return redirect(url_for('chat.join_room', rn=new_room.name))
    return jsonify(result="fail", type="create", message='Sorry, the name is alreay existed, please change another.')

@chat_bp.route('/search',  methods=['POST'])
def search_room():
    print("in search_room")
    name = request.form['room']
    room = Room.query.filter_by(name=name).first()
    if room is not None:
        return jsonify(result="success",type="search", data={'room':room.name, 'is_public': True if room.password else False, 'join_url':url_for('chat.join_room', rn=room.name)})
    return jsonify(result="fail",type="search", message='Can\'t find the room.')


@chat_bp.route('/join/<string:rn>', methods=['POST'])
def join_room(rn):
    room = Room.query.filter_by(name=rn).first()
    if room is None:
        return jsonify(result="fail",type="joinRoom", message="The room doesn't exist.")
    if room.password:
        password = request.form.get("password",None)
        if password != room.password:
            return jsonify(result="fail", type="joinRoom", message="Password is incorrect.")
    if redis.hget("roomstatus", room.name) == "1":
        return jsonify(result="fail", type="joinRoom", message="The room is on the game, please join later.")
    elif (current_user not in room.users) and len(room.users) >= 6:
        return jsonify(result="fail", type="joinRoom", message="Sorry, the room is already full.")
    elif current_user in room.users:
        return jsonify(result="success", type="joinRoom", data={"room": room.name,"room_url": url_for('chat.room', rn=room.name)})
    try:
        room.users.append(current_user)
        db.session.commit()
    except:
        return jsonify(result="fail", type="joinRoom", dmessage="Sorry, the room is already full.")
    redis.zadd(room.name + "_score", {current_user.nickname: 0})
    redis.hset(room.name, current_user.nickname, 0)
    return jsonify(result="success", type="joinRoom",
                   data={"room": room.name, "room_url": url_for('chat.room', rn=room.name)})

@chat_bp.route('/leave/<string:rn>')
def leave_room(rn):
    print(current_user.nickname, "run leave room command")
    room = Room.query.filter_by(name=rn).first()
    if room is not None and current_user in room.users:
        redis.zrem(room.name + "_score", current_user.nickname)
        redis.hdel(room.name, current_user.nickname)
        room.users.remove(current_user)
        if len(room.users) == 0 :
            print("clear the room", room.name)
            redis.srem("room",room.name)
            db.session.delete(room)
        db.session.commit()
    return redirect(url_for('chat.platform'))


@chat_bp.route('/room/<rn>/leader', defaults={'user':None})
@chat_bp.route('/room/<rn>/leader/<user>')
def leader_change(rn,user):
    room = Room.query.filter_by(name=rn).first()
    members = [i.nickname for i in room.users]
    print("in leader change function:",members,room.leader)
    if user and user in members:
        candidate = user
        # leader = room.set_leader(user)
    elif len(members) == 1 and members[0] == room.leader:
        return jsonify(result="success", type="changeLeader", data={"room": room.name, "leader": room.leader})
    else:
        candidate = random.choice([i for i in members if i !=room.leader])
    leader = room.set_leader(candidate)
    db.session.commit()
    print("new leader is ", leader)
    return jsonify(result="success", type="changeLeader", data={"room": room.name, "leader":leader})


@chat_bp.route('/messages/<string:rn>')
def get_messages(rn):
    page = request.args.get('page', 1, type=int)
    room = Room.query.filter_by(name=rn).first()
    pagination = Message.query.filter_by(room=room).order_by(Message.timestamp.desc()).paginate(
        page, per_page=30 ,error_out=False)
    messages = pagination.items
    return render_template('chat/_messages.html', messages=messages[::-1])


@chat_bp.route('/checkanswer/<string:rn>')
def check_answer(rn):
    answer = request.args.get('answer')
    print("check answer:",answer)
    room = Room.query.filter_by(name=rn).first()
    if redis.hget("roomstatus", room.name) == "1":
        correct_answer = redis.hget("topic", room.name)
        if answer.lower() == correct_answer.lower():
            redis.zincrby(room.name + "_score", 10, current_user.nickname)
            score = redis.zscore(room.name + "_score", current_user.nickname)
            return jsonify(result="correct", score=score, room=room.name, user=current_user.nickname)
    return jsonify(result="wrong", room=room.name)


@chat_bp.route('/gettopic/<string:rn>')
def get_topic(rn):
    room = Room.query.filter_by(name=rn).first()
    if current_user.nickname == room.leader:
        word = Word.query.get(random.randint(1, Word.query.count()))
        print(word)
        redis.hset("roomstatus", room.name, 1)
        redis.hset("topic", room.name, word.name)
        print("get topic:",word.name)
        return jsonify(result="success", topic=word.name, room=room.name)
    return jsonify(result="fail", topic=None, room=room.name)


@chat_bp.route('/room/<string:rn>/refreshscores')
def roomscore(rn):
    room = Room.query.filter_by(name=rn).first()
    rank = redis.zrevrange(room.name + "_score", 0, -1, withscores=True, score_cast_func=int)
    rank = dict(rank)
    return jsonify(rank=rank, rank_html=render_template('chat/_ranks.html', users=room.users, rank=rank),
                   room=room.name)


@chat_bp.route('/room/<string:rn>/refreshleader')
def refreshleader(rn):
    room = Room.query.filter_by(name=rn).first()
    return jsonify(leader_html=render_template('chat/_top_bar_status_users.html', users=room.users, leader=room.leader),
                   room=room.name,
                   leader=room.leader)


@chat_bp.route('/room/<string:rn>/ready')
def refreshreadystatus(rn):
    room = Room.query.filter_by(name=rn).first()
    users_status = redis.hgetall(room.name)
    all_ready = True
    for user,status in users_status.items():
        if user != room.leader and status == "0":
            all_ready = False
            break
    print(users_status)
    return jsonify(
        status_html=render_template('chat/_top_bar_status_users.html', users=room.users, leader=room.leader,
                                               status=users_status),
        userStatus=users_status,
        allReady = all_ready,
        room=room.name)

main/blueprints/index.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, app

index_bp = Blueprint('index',__name__)

@index_bp.route('/')
def index():
    return render_template('index.html')

@index_bp.route('/howToPlay')
def howToPlay():
    return render_template('howToPlay.html')

@index_bp.route('/test')
def test_page():
    return str(1/0)

main/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <!-- Site Properties -->
    <title>{% block title %}{% endblock %} - Guess What I Draw</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block css %}{% endblock %}
</head>
<body>

<!--{% for message in get_flashed_messages(with_categories=True) %}-->
<!--    <div class="ui message {{ message[0] }} msg ">-->
<!--      <i class="close icon"></i>-->
<!--      <div class="header">-->
<!--        Message-->
<!--      </div>-->
<!--      <p>{{ message[1] }}</p>-->
<!--    </div>-->
<!--{% endfor %}-->

<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
    <a class="active item" href="{{ url_for('index.index') }}">Home</a>
    <a class="item" href="{{ url_for('index.howToPlay') }}">How to play</a>
    <a class="item" href="{{ url_for('chat.platform') }}">Get started</a>
    {% if current_user.is_authenticated %}
    <a href="{{ url_for('auth.logout') }}" class="item">Log out</a>
    {% else %}
    <a href="{{ url_for('auth.login') }}" class="item">Log in</a>
    <a href="{{ url_for('auth.register') }}" class="item">Sign up</a>
    {% endif %}
</div>

{% block main %}
{% endblock %}


<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
{% block script%}{% endblock %}
</body>
</html>

main/templates/howToPlay.html
{% extends 'base.html' %}
{% block title %} index {% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block main %}

<div class="pusher">
    <!-- Page Contents -->
    <div class="ui container">
        <div class="ui large secondary menu">
            <a class="toc item">
                <i class="sidebar icon"></i>
            </a>
            <a class="header item" href="{{ url_for('index.index') }}">Home</a>
            <a class="header active item">How to play</a>
            <a class="header item">Get started</a>
            <div class="right menu">
                {% if current_user.is_authenticated %}
                <div class="item">
                    <div class="ui button dropdown">
                        {{ current_user.nickname }}
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            <a href="{{ url_for('auth.logout') }}" class="item">Log out</a>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="item">
                    <a href="{{ url_for('auth.login') }}" class="ui button">Log in</a>
                </div>
                <div class="item">
                    <a href="{{ url_for('auth.register') }}" class="ui primary button">Sign Up</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="ui padded center aligned basic segment">
        <div class="ui container">
            <div class="ui embed" data-source="youtube" data-url="https://www.youtube.com/embed/g0N08l09y_A">
            </div>
        </div>
    </div>


    <div class="ui inverted segment footer-not-index">
        <div class="ui container">
            <div class="ui inverted equal height centered grid">
                <div class="three wide column">
                    <h4 class="ui inverted header">About</h4>
                    <div class="ui inverted link list">
                        <a href="#" class="item">Report issue</a>
                        <a href="#" class="item">Contact me</a>
                        <a href="#" class="item">FAQ</a>
                    </div>
                </div>
                <div class="three wide column">
                    <h4 class="ui inverted header">&copy; 2021 Fanco</h4>
                </div>
                <div class="seven wide column">
                    <h4 class="ui inverted header">If you like the project</h4>
                    <p>please feel free give me a thumbup.</p>
                    <a href="https://github.com/fancofang/GuessIDraw" class="item">github</a>
                </div>
            </div>
        </div>
    </div>
    <!--<div class="ui bottom fixed inverted menu">-->


    <!--</div>-->
    <!--<div class="ui text container">-->
    <!--    <div class="ui one column grid">-->
    <!--      <div class="column">1123</div>-->
    <!--    </div>-->
    <!--</div>-->
</div>

{% endblock %}

{% block script%}
<script>
    $(document)
        .ready(function () {
            // fix menu when passed
            $('.ui.embed').embed();
            // create sidebar and attach to menu open
            $('.ui.sidebar').sidebar('attach events', '.toc.item')
            ;
        })
    ;
</script>
{% endblock %}



<!--<iframe width="1280" height="720" src="https://www.youtube.com/embed/g0N08l09y_A" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>-->

main/templates/index.html
{% extends 'base.html' %}
{% block title %} index {% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block main %}

<!-- Following Menu -->
<div class="ui large top fixed hidden menu">
    <div class="ui container">
        <a class="active item"  href="{{ url_for('index.index') }}">Home</a>
        <a class="item" href="{{ url_for('index.howToPlay') }}">How to play</a>
        <a class="item" href="{{ url_for('chat.platform') }}">Get started</a>
        <div class="right menu">
            {% if current_user.is_authenticated %}
            <div class="item">
                <div class="ui button dropdown">
                    {{ current_user.nickname }}
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <a href="{{ url_for('auth.logout') }}" class="item">Log out</a>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="item">
                <a href="{{ url_for('auth.login') }}" class="ui button">Log in</a>
            </div>
            <div class="item">
                <a href="{{ url_for('auth.register') }}" class="ui primary button">Sign Up</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<!-- Page Contents -->
<div class="pusher">
    <div class="ui vertical masthead center aligned segment landing-image">
        <div class="ui container">
            <div class="ui large secondary inverted menu">
                <a class="toc item">
                    <i class="sidebar icon"></i>
                </a>
                <a class="header active item" href="{{ url_for('index.index') }}">Home</a>
                <a class="header item" href="{{ url_for('index.howToPlay') }}">How to play</a>
                <a class="header item" href="{{ url_for('chat.platform') }}">Get started</a>
                <div class="right menu">
                    {% if current_user.is_authenticated %}
                    <div class="item">
                        <div class="ui button dropdown">
                            {{ current_user.nickname }}
                            <i class="dropdown icon"></i>
                            <div class="menu">
                                <a href="{{ url_for('auth.logout') }}" class="item">Log out</a>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <div class="item">
                        <a href="{{ url_for('auth.login') }}" class="ui button">Log in</a>
                    </div>
                    <div class="item">
                        <a href="{{ url_for('auth.register') }}" class="ui primary button">Sign Up</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="ui text container intro">
            <h1 class="ui header inverted">
                Guess What I Draw ?
            </h1>
            <h2 class="ui inverted">Enjoy your drawing and guessing time with your friend.</h2>
            <p>* No Drawing Skill Required</p>
            <a href="{{ url_for('chat.platform') }}" class="ui huge primary button">Get Started <i class="right arrow icon"></i></a>
        </div>
    </div>

    <div class="ui vertical stripe quote segment">
        <div class="ui equal width stackable internally celled grid">
            <div class="right aligned row">
                <div class="left floated column ui card">
                    <div class="ui small rounded image right floated">
                        <img src="{{ url_for('static', filename='images/painter.jpg') }}">
                    </div>
                    <h3 class="margin">Draw whatever you want from a given word.</h3>
                    <h3 class="margin">Wiggle you finger to create a doodle masterpiece!</h3>
                    <p>when you are the painter</p>
                </div>
            </div>
        </div>
    </div>

    <div class="ui vertical stripe quote segment">
        <div class="ui equal width stackable internally celled grid">
            <div class="left aligned row">
                <div class="right floated column ui card">
                    <div class="ui small rounded image left floated">
                        <img src="{{ url_for('static', filename='images/guesser.jpg') }}">
                    </div>
                    <h3 class="margin">Even though you answer incorrect,</h3>
                    <h3 class="margin">it's a good chance to saracasm your friend!</h3>
                    <p>when you are the guesser</p>
                </div>
            </div>
        </div>
    </div>



    <div class="ui inverted vertical footer segment">
        <div class="ui container">
            <div class="ui stackable inverted divided equal height grid">
                <div class="three wide column">
                    <h4 class="ui inverted header">About</h4>
                    <div class="ui inverted link list">
                        <a href="#" class="item">Report issue</a>
                        <a href="#" class="item">Contact me</a>
                        <a href="#" class="item">FAQ</a>
                    </div>
                </div>
                <div class="three wide column">
                    <h4 class="ui inverted header">&copy; 2021 Fanco</h4>
                </div>
                <div class="seven wide column">
                    <h4 class="ui inverted header">If you like the project</h4>
                    <p>please feel free give me a thumbup.</p>
                    <a href="https://github.com/fancofang/GuessIDraw" class="item">github</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script%}
<script>
    $(document)
        .ready(function () {
            // fix menu when passed
            $('.masthead')
                .visibility({
                    once: false,
                    onBottomPassed: function () {
                        $('.fixed.menu').transition('fade in');
                    },
                    onBottomPassedReverse: function () {
                        $('.fixed.menu').transition('fade out');
                    }
                })
            ;

            $('.ui.dropdown')
                .dropdown();

            // create sidebar and attach to menu open
            $('.ui.sidebar').sidebar('attach events', '.toc.item')
            ;

        })
    ;
</script>
{% endblock %}